language: java
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_5d1cc3ab8481_key -iv $encrypted_5d1cc3ab8481_iv -in travis-secrets.tar.enc -out travis-secrets.tar -d
  - tar xvf travis-secrets.tar
  - gpg --import travis/public.key
  - gpg --allow-secret-key-import --import travis/private.key
install: true
script: mvn clean deploy --settings travis/settings.xml
